development:
  GOOGLE_CLIENT_ID: '542499740300-t8mks0uof9q1hd7qn6osf75vat78d39d.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'k5uKFFfS8JVIJx4vq2upNsDE'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_CLIENT_ID: '542499740300-t8mks0uof9q1hd7qn6osf75vat78d39d.apps.googleusercontent.com'
  GOOGLE_SECRET_KEY: 'k5uKFFfS8JVIJx4vq2upNsDE'